QMGR=$1
ENV=$2
MAXDEPTH=$3
. /$ENV/usr/mqm/bin/setmqenv -s

runmqsc $QMGR <<STREAM
DEFINE QLOCAL(ALM.LOCATION.RECEIVE.SEQ) DESCR('Devonway Location Queue') MAXDEPTH(10000) DEFPSIST(YES) REPLACE
DEFINE QLOCAL(ALM.LOCATION.RECEIVE.SEQ.BACKOUT) DESCR('Devonway Location Queue') MAXDEPTH(10000) DEFPSIST(YES) REPLACE
end
STREAM
