QMGR=$1
ENV=$2
MAXDEPTH=$3
. /$ENV/usr/mqm/bin/setmqenv -s

runmqsc $QMGR <<STREAM

DEFINE QLOCAL('ALM.LOCATION.RECEIVE.SEQ')  DESCR('Devonway Location Queue')  DEFPSIST(YES) MAXDEPTH (1000000) REPLACE
DEFINE QLOCAL('ALM.LOCATION.RECEIVE.SEQ.BACKOUT')  DESCR('Devonway Location Queue')  DEFPSIST(YES) MAXDEPTH (1000000) REPLACE
end
STREAM
